// ─────────────────────────────────────────────────────────────────────────
// THE LIST. This is the whole point: adding a service here creates its entire
// pipeline on the next seed run. Nothing is clicked. Nothing is configured in
// the UI. The jobs are a pure function of this file.
//
// removeAction('DELETE') is set on the seed job, so removing a service here
// DELETES its job. The jobs converge on this file in both directions -- the
// same reconciliation idea ArgoCD applies to the cluster, one layer up.
// ─────────────────────────────────────────────────────────────────────────
def services = [
    'edge-gateway',
    'auth-svc',
    'catalog-svc',
    'cart-svc',
    'order-svc',
    'payment-worker',
    'notify-svc',
    'media-svc',
]

def gitHubUser = 'pratikpagariya'
def appsRepo   = "https://github.com/${gitHubUser}/shopglobe-apps.git"
def infraRepo  = "https://github.com/${gitHubUser}/shopglobe-infra.git"

folder('shopglobe') {
    description('Generated by the seed job from jenkins/jobdsl/. Edits made here are overwritten on the next run.')
}

services.each { svc ->
    pipelineJob("shopglobe/${svc}") {
        description("Build -> scan -> push -> GitOps deploy for ${svc}. Generated by Job DSL; do not edit in the UI.")

        parameters {
            // SERVICE is how ONE shared Jenkinsfile knows which service it is
            // building. Eight jobs, one pipeline definition to maintain.
            stringParam('SERVICE', svc, 'Service being built (set by Job DSL)')
            stringParam('GIT_REF', 'main', 'Branch or tag to build')
            booleanParam('DEPLOY', true, 'Commit the new image tag to the gitops repo')
        }

        properties {
            // Two builds of the same service racing to write the gitops repo
            // will conflict on push. Serialise them.
            disableConcurrentBuilds()
        }

        logRotator {
            numToKeep(20)
            artifactNumToKeep(5)
        }

        definition {
            cpsScm {
                scm {
                    git {
                        remote { url(appsRepo) }
                        branch('${GIT_REF}')
                    }
                }
                scriptPath('Jenkinsfile')
                lightweight(false)
            }
        }
    }
}

// Infrastructure gets a differently SHAPED pipeline, not just different steps:
// plan always, apply only behind a manual gate. Different blast radius,
// different controls.
pipelineJob('shopglobe/terraform-plan') {
    description('fmt -> validate -> tflint -> plan. Apply is a separate, gated job.')

    parameters {
        choiceParam('STACK', ['prod', 'stage', 'dev'], 'Which stack to plan')
    }

    logRotator {
        numToKeep(20)
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote { url(infraRepo) }
                    branch('main')
                }
            }
            scriptPath('Jenkinsfile.terraform')
            lightweight(false)
        }
    }
}
